(define (replace f x a)
   (if (null? x) '()
      (let ((t (replace f (cdr x) a)))
         (if (f (car x))
            (cons a t)
            (cons (car x) t)
         )
      )
   )
)

(replace (lambda (x) (not (pair? x))) '((A) B (C) D E (F)) 'Z)